In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd

In [17]:
file_path = "diabetes_012_ready_to_model.csv"

In [18]:
df_raw = pd.read_csv(file_path)

In [19]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229712 entries, 0 to 229711
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HighBP                229712 non-null  float64
 1   HighChol              229712 non-null  float64
 2   CholCheck             229712 non-null  float64
 3   Smoker                229712 non-null  float64
 4   Stroke                229712 non-null  float64
 5   HeartDiseaseorAttack  229712 non-null  float64
 6   PhysActivity          229712 non-null  float64
 7   Fruits                229712 non-null  float64
 8   Veggies               229712 non-null  float64
 9   HvyAlcoholConsump     229712 non-null  float64
 10  AnyHealthcare         229712 non-null  float64
 11  NoDocbcCost           229712 non-null  float64
 12  DiffWalk              229712 non-null  float64
 13  Sex                   229712 non-null  float64
 14  GenHlth               229712 non-null  float64
 15  Age                   229712 non-null  float64
 16  Education             229712 non-null  float64
 17  Income                229712 non-null  float64
 18  BMI                   229712 non-null  float64
 19  MentHlth              229712 non-null  float64
 20  PhysHlth              229712 non-null  float64
 21  Diabetes_012          229712 non-null  float64
dtypes: float64(22)
memory usage: 38.6 MB

In [1]:
# extract the 8 features in the template
import json
template_json = "../tabular_template_building/tabular_feature_template.json" 

with open(template_json, "r") as f:
  templete = json.load(f)

In [2]:
t_features = templete["features"]
t_mask = templete["masks"]

t_features

['Age',
 'Sex',
 'BMI',
 'GenHlth',
 'HighBP',
 'DiffWalk',
 'HighChol',
 'HeartDiseaseorAttack']

In [22]:
df_8_features = df_raw.copy()

df_8_features = df_8_features[t_features]
df_8_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229712 entries, 0 to 229711
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Age                   229712 non-null  float64
 1   Sex                   229712 non-null  float64
 2   BMI                   229712 non-null  float64
 3   GenHlth               229712 non-null  float64
 4   HighBP                229712 non-null  float64
 5   DiffWalk              229712 non-null  float64
 6   HighChol              229712 non-null  float64
 7   HeartDiseaseorAttack  229712 non-null  float64
dtypes: float64(8)
memory usage: 14.0 MB

In [23]:
for col in t_mask:
    df_8_features[col] = 1

df_8_features.head()

,Age,Sex,BMI,GenHlth,HighBP,DiffWalk,HighChol,HeartDiseaseorAttack,Age_mask,Sex_mask,BMI_mask,GenHlth_mask,HighBP_mask,DiffWalk_mask,HighChol_mask,HeartDiseaseorAttack_mask
0,0.295419,0.0,1.667028,2.252865,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1
1,-0.351000,0.0,-0.543046,0.374534,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1
2,0.295419,0.0,-0.101031,2.252865,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1
3,0.941838,0.0,-0.248370,-0.564631,1.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1
4,0.941838,0.0,-0.690385,-0.564631,1.0,0.0,1.0,0.0,1,1,1,1,1,1,1,1

In [24]:
df_label = df_raw["Diabetes_012"]
df_tabular_ready = pd.concat(
    [df_8_features, df_label], 
    axis=1
    )

df_tabular_ready.head()

,Age,Sex,BMI,GenHlth,HighBP,DiffWalk,HighChol,HeartDiseaseorAttack,Age_mask,Sex_mask,BMI_mask,GenHlth_mask,HighBP_mask,DiffWalk_mask,HighChol_mask,HeartDiseaseorAttack_mask,Diabetes_012
0,0.295419,0.0,1.667028,2.252865,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1,0.0
1,-0.351000,0.0,-0.543046,0.374534,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,0.0
2,0.295419,0.0,-0.101031,2.252865,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1,0.0
3,0.941838,0.0,-0.248370,-0.564631,1.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,0.0
4,0.941838,0.0,-0.690385,-0.564631,1.0,0.0,1.0,0.0,1,1,1,1,1,1,1,1,0.0

In [25]:
# train-val-test split
# train + val vs test
tabular_train_val, tabular_test = train_test_split(
    df_tabular_ready, 
    test_size    = 0.2, 
    random_state = 42, 
    stratify = df_tabular_ready["Diabetes_012"]
    )

# train vs val
tabular_train, tabular_val = train_test_split(
    tabular_train_val, 
    test_size    = 0.25, 
    random_state = 42, 
    stratify = tabular_train_val["Diabetes_012"]
    )

In [26]:
# save to 3 CSVs
tabular_train.to_csv("diabetes_012_train.csv", index = False)
tabular_val.to_csv  ("diabetes_012_val.csv"  , index = False)
tabular_test.to_csv ("diabetes_012_test.csv" , index = False)

print("Train/Val/Test saved successfully.")

Train/Val/Test saved successfully.